
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/models/med_pipe/application_record.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"
