name: "med_pipe"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: devcontainer.env
    volumes:
    - ..:/app:cached
    command: sleep infinity
    depends_on:
    - mysql
  mysql:
    image: mysql:8.0
    ports:
    - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
    - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql-data:
