name: Publish gem to RubyGems

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.3'
      - uses: rubygems/release-gem@v1
