name: test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version:
          - 3.3
        rails-version:
          - 6.1
          - 7.2
    timeout-minutes: 10
    services:
      mysql:
        image: bitnami/mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      RAILS_ENV: test
      BUNDLE_GEMFILE: ${{ github.workspace }}/.github/gemfiles/Gemfile.rails-${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: remove Gemfile.lock and ruby version
        run: |
          rm -f Gemfile.lock
          rm -f .ruby-version
      - uses: ruby/setup-ruby@v1 # ruby-versionはprojectの.ruby-versionを読む
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: DB create and migrate
        run: |
          cp .github/database.yml spec/dummy/config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Test with RSpec
        run: bundle exec rspec
